### ISSUE TITLE
demo 2有错误

### ISSUE THREAD

**Issue by chaofengc** [PKU-YuanGroup/ChatLaw#2]
刑法第二百六十七条不是故意伤害罪，而是第二百三十四条。二百六十七条为: 抢劫罪。
详见维基百科: https://zh.wikisource.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%88%91%E6%B3%95

另附上ChatGPT答案:

![chatgpt_law](https://github.com/PKU-YuanGroup/ChatLaw/assets/7187685/3866c026-91b2-4694-a8c9-49d2600bbadb)

**Comment by qqingzheng** [comment]
对您造成了困扰，实在不好意思。开源与在线体验中的版本为学术demo版，可能在准确性上有所欠缺。感谢您指出的问题，我们会努力改进。

**Comment by chaofengc** [comment]
感谢你们的工作和及时回复！
