### ISSUE TITLE
合同法是不是在2021年1月1日后失效了，作者有没有注意更新这一点

### ISSUE THREAD

**Issue by ShuangLyu** [PKU-YuanGroup/ChatLaw#7]
2021年1月1日民法典生效后，《中华人民共和国民法通则》、《中华人民共和国担保法》、《中华人民共和国合同法》、《中华人民共和国物权法》、《中华人民共和国民法总则》等法律文件已经失效

**Comment by JessyTsu1** [comment]
感谢提醒，这是数据清洗的问题，因为之前人手比较少，没有对新旧法做完善的清洗，最新的模型会注意到这一点
