### ISSUE TITLE
群满了，求拉我入微信群，微信号dandanshanhu，我们也在训练大模型

### ISSUE THREAD

**Issue by BeiJingChengXiTech** [PKU-YuanGroup/ChatLaw#8]

**Comment by qq6690876** [comment]
+1.
微信号: qq692763892

**Comment by hzhfgt** [comment]
+1
微信号：zhchqbz95

**Comment by SZ-ing** [comment]
+1
微信号：17312888796

**Comment by wuwenrui** [comment]
+1
微信号：Codingrui

**Comment by soriqe** [comment]
+1
微信号：s29201068

**Comment by qiyuanzhang520** [comment]
+1微信号 zhangqiyuan520

**Comment by Xchuantangfeng** [comment]
+1 微信号：qainyi4464599

**Comment by ericperfect** [comment]
+1 微信号：594004442

**Comment by buzhaodi** [comment]
+1 微信号：buzhaodi

**Comment by EternalKsana** [comment]
+1 微信号：EternalKsana
谢谢啦

**Comment by guoboyue** [comment]
+1 1140663116

**Comment by yuzhaojing** [comment]
+1 15180453201

**Comment by Batmana** [comment]
+1 微信号: Laffy-128

**Comment by magicleo** [comment]
+1 微信号： leo_liu_

**Comment by HaKLMTT** [comment]
微信号:     wx15201338223         

多谢

**Comment by ScottishFold007** [comment]
微信号：g18818233178

**Comment by poltawa** [comment]
大模型产品从业者，想进群共同交流，微信号，kurenai1379

**Comment by ArthurWei0929** [comment]
+1，微信号：18810918780

**Comment by zhihao-chen** [comment]
+1 微信号：764140207

**Comment by HopeZhi** [comment]
+1 微信号：Zhichenhaozzz 谢谢啦

**Comment by YangQianTian** [comment]
+1 微信号:22387761
谢谢

**Comment by wa114d** [comment]
+1，求拉，微信号：sfzhang8866
谢谢

**Comment by jun-jing** [comment]
+1，求拉，微信号：tewbooathtb
谢谢

**Comment by walkingdaniel** [comment]
+1，求拉，微信号：denghuan223

**Comment by Vic-Victor** [comment]
+1，求拉，微信号：Junwei_125

**Comment by sunshuaicode** [comment]
+1，求拉，微信号：its_long_story_shuai

**Comment by ChaohuaZhang** [comment]
+1，求拉，微信号：Debby_CHUA

**Comment by Wizhiai** [comment]
+1，求拉，微信号：niwodoushi250

**Comment by zh999991** [comment]
+1，求拉，微信号：QQ948691620

**Comment by ksy2015** [comment]
+1，求拉，微信号luo2luo4

**Comment by yejiahaoye** [comment]
+1，求拉，微信号wxid_1065350652214

**Comment by BeiJingChengXiTech** [comment]
![image](https://github.com/PKU-YuanGroup/ChatLaw/assets/134131262/8168da4f-b2fe-4e3d-820f-2f0c33cf5ddf)
